### PR TITLE
Allow simple customization of label's class attributes

### PR DESCRIPTION
**Pull request by GeJ**
Add optional attributes to Field and Field::Choice to allow to customize label tags.

This makes it easier to use HTML::Shakan with CSS libraries like Bootstrap.

### CODE REVIEW

**Comment by Songmu** [comment]
Good feature!

[nit] Is there any reason that the predicate methods have `_css` postfix? I think `_cls` or `_class` is better.

**Comment by GeJ** [comment]
Indeed, I struggled with the naming of those attributes and methods so they wouldn't be too verbose. I amended the PR with a new patch so that the predicate methods match the attribute's name.
Thank you for the suggestion.

**Comment by Songmu** [comment]
Thank you!

**Comment by Songmu** [comment]
Released as 2.10.

**Pull request merged**
